### ISSUE TITLE
Installation problem. Documentation?

### ISSUE THREAD

**Issue by alejandri** [hosseinhkj/Neveshtar#4]
Heello, i want installing and test your app but i can not install normally via "composer install" y not found documentation with steps to install this package.

This error show me:

D:\xampp\htdocs\nevestar>composer install

Warning: This development build of composered to update it by running "C:\ProgramData\C
update" to get the latest version.
Loading composer repositories with package iInstalling dependencies (including require-d
Your requirements could not be resolved to a

  Problem 1 - Installation request for intervention ention/image[2.1.3].
    - intervention/image 2.1.3 requires ext- nsion fileinfo is missing from your system.

**Comment by hosseinhkj** [comment]
This CMS is not yet released. Therefore the documentation still needs to be completed, before the iniatial release. However you can simply 

- download the source code 
- Meet the requirements of Laravel 5 from the docs in www.laravel.com
- Put the sql file in a mysql database
- Add the mysql details in the .env file (rename it from example.env)
- Create a virtual host for it pointing to the "/public" folder in the root
- Run the virtual host in your browser (e.g http://localhost)
- Register a new user (which will be the admin user)
- Put some data in the admin (e.g http://localhost/admin)
- And start playing with the CMS

However a lot of the modules are yet to be completed. But I repeat as soon as there is an initial release all the documentation will be provided.

Please let me know if the steps described above are insufficient and you run in to any errors or problems.
Thanks in advance.

**Comment by alejandri** [comment]
Thanks !
